version: '3'

services:
  db:
    image: mysql/mysql-server:8.0.20
    container_name: ComicVerwaltung_DB
    restart: always
    environment:
      MYSQL_DATABASE: ComicVerwaltung
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
