spring:
  profiles:
    active: local

  flyway:
    locations: classpath:db/migration
    user: admin
    password: admin



  application:
    name: ComicVerwaltung

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/ComicVerwaltung
    username: admin
    password: admin